### ISSUE TITLE
Not reporting error messages

### ISSUE THREAD

**Issue by HauntedSmores** [Shopify/node-themekit#19]
### Problem

node-themekit is not reporting error messages properly. My experience seeing this issue is when using the watch command (I believe its the same for other commands as well but I will have to test). Attached is a screen shot showing the same command, updating the same file, only adding a linebreak in my text editor - first using `theme watch` which prints a 409 error message, and then using `shopify-themekit watch` which fails silently.

![theme-kit-ss](https://user-images.githubusercontent.com/20644458/32965779-adf1e4c6-cba5-11e7-8f78-bb02d2e930f9.jpg)

**Comment by erickzhao** [comment]
Should be fixed since Release 1.0.0 (#23).
