### ISSUE TITLE
Not enough Congratulations and acknowledgements for your work :)

### ISSUE THREAD

**Issue by agentlewis** [Shopify/node-themekit#24]
:sparkles::sparkles::sparkles::sparkles:Congratulations on the V1.0.0 Release, thats a huge milestone. Its time to party! :sparkles::sparkles::sparkles::sparkles: 

I will now be upgrading the handful of shops I have to use this repo as a local dependency in place of the global theme install - supporting juniors just got a little easier for me :)

![Colton never gets old](https://i.giphy.com/media/5iXTLFjce2qcw/giphy.webp)
And dance...

**Comment by NathanPJF** [comment]
Thanks @agentlewis - that's very kind of you to say 😄 

I'll be sure this reaches other folks who have worked on this project!
