### ISSUE TITLE
Sharing my scripts - keen for input and suggestions :)

### ISSUE THREAD

**Issue by agentlewis** [Shopify/node-themekit#26]
### Problem
Previously I had no trouble with overwrites when using the manifest. Now my always pull before push deployment strategy is deleting my local files. Not a problem I thought - I have git, buttt I realised I don't want to commit code I am currently working on until i have tested it.

So I have now rewritten my scripts thus 

```json
 "scripts": {
    "check": "test $(git ls-files --exclude-standard --others | wc -l) -gt 0 && (echo 'Untracked files found in theme'; exit 1) || exit 0;",
    "download:prod": "git stash && shopify-themekit download --env production",
    "deploy:prod": "shopify-themekit deploy --env production",
    "data:prod": "shopify-themekit download --env production config/*.json",
    "sync:prod": "run-s data:prod deploy:prod",
    "zip": "zip -r $npm_package_name-$(date +'%m_%d_%Y') assets config layout locales sections snippets templates"
  },
```

The two critical scripts for not overwriting remote data are: `download:prod` & `data:prod`. I am not anticipating using `download:prod` very often - its main purpose is to pull down a lot of changes that the client has made. The more important one is `data:prod` which pulls down configs that change a lot as the client updates pages.

I realise as I am writing this that I will have to have a much more stringent deployment process - first testing it on staging and then deploying to master - after a `download:prod`

This is a little unfortunate as it basically adds an extra cost to doing small jobs. To date with the manifest + git I was comfortably working with just a production store. This allowed me to deliver more value to my clients for the budget they had.

So I am out for suggestions to my scripts to try and make this so that I can still do small jobs with one store quick and dirty. 

One idea I had was to get the output of a git status (or other similar function) and get the paths and only push those up. That way I am only deploying the current files I have changed. Another is to test git for untracked files and abort the download if there are. ie adding even the most simple page will mean any downloaded deletes will be traceable. *edit: added 'check' to the scripts - first attempt with low bashfu* (which would happen if you deployed the untracked file - then later downloaded it for "safety sake" before you intended to deploy again)

**Oh and before you say it** - I know this is what `watch` is for. But when you are travelling and running on crappy internet connections (currently Cape Town) this just doesn't cut it.

So thoughts and suggestions???

**Comment by andyw8** [comment]
@agentlewis thanks for sharing your script. As this isn't a bug report or specific feature request, it may be better suited for the [Partners Community](https://www.shopify.ca/partners/community).
