### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by erickzhao** [Shopify/node-themekit#30]
Since the `v1.0.0` release, we've had a test suite that covers a good deal of the code. Would it be possible to integrate Travis CI as in other Shopify open-sourced libraries?

cc @t-kelly.

**Comment by t-kelly** [comment]
Yep! Take a look at the other Slate repo's `.travis.yml` files and we'll get it up and running.

**Comment by andyw8** [comment]
Was Travis integration working previously? It seems to have been lost.

**Comment by erickzhao** [comment]
@andyw8 from what I recall, the integration was never set up after the config was added in #31.

**Comment by andyw8** [comment]
I've created a helpdesk ticket (#SR-114997).

**Comment by andyw8** [comment]
It's working: https://github.com/Shopify/node-themekit/pull/66
