### ISSUE TITLE
Configuring timeout

### ISSUE THREAD

**Issue by rossb** [Shopify/node-themekit#32]
Could I make a request that the timeout setting for network requests to ThemeKit be made configurable please? On a slow broadband connection (think ≈5 MEG) it's often necessary to increase the timeout from its default value to reliably complete file transfer requests.

This can be directly configured in ThemeKit, but I believe it's not currently possible to configure it using node-themekit (which in turn prevents it being configured using the latest version of Slate).

**Comment by t-kelly** [comment]
@rossb Sorry if my last response wasn't clear -- best to open this issue in [Themekit](https://github.com/Shopify/themekit) because this lib is just a wrapper.
