### ISSUE TITLE
How should I update themekit

### ISSUE THREAD

**Issue by agentlewis** [Shopify/node-themekit#33]
### Problem

Currently I am getting a warning that there is an update for themekit but there is no update for node-themekit. 

How should I go about updating the dependancy?

Thanks
D

**Comment by t-kelly** [comment]
You can open a PR that [updates the version here](https://github.com/Shopify/node-themekit/blob/065e538ca2a6a3a94e042bb0a8180f7d5405b0d1/lib/config.js#L5) and I'll publish a new version of `node-themekit` 😄

**Comment by NathanPJF** [comment]
@t-kelly The latest version of [ThemeKit is `1.0.0`](https://github.com/Shopify/themekit/releases) which includes breaking changes. Maybe most notably the `upload` command is gone and it’s now `deploy`. So I wouldn't want to bump to a major release in our package, better to give people a way to opt-in to it.

@erickzhao Is this something you'd want to take on? Providing a way for folks to specify the `version` that the `config` file will down on install? Something like `yarn install @shopify/themekit --themekit=1.0.0`.  No worries if you're busy; just give us a heads up if this is something you'd like to own 😄

**Comment by erickzhao** [comment]
Hey y'all!

After doing a quick google search, I think this is something that we could do with `npm dist-tag` ([link](https://docs.npmjs.com/adding-dist-tags-to-packages)), giving something like `@shopify/themekit@next`. I've actually never published anything to npm and don't have access to the registry for `node-themekit`, though.

@NathanPJF maybe this one is out of my hands? 😅
