### ISSUE TITLE
themekit.command does not reject promises on error

### ISSUE THREAD

**Issue by nschomberg** [Shopify/node-themekit#34]
### Problem

node-themekit's `command` function does not throw any JS errors or reject the promise it returns if it runs into exceptions.

### Replication steps

- Run into error during a command (You can do this by deleting a file that is supposed to be `deploy`ed, or having bad store credentials, or bad theme id)
- themekit will output an error message to the terminal after finishing the command
- themekit will not throw any errors, reject the promise, or return anything useful

Reduced test case:

```js
const themeKit = require('@shopify/themekit'); // @1.0.1

themeKit
  .command(
    'deploy',
    {
      store: `anything.myshopify.com`,
      password: 'anything',
    },
    {
      cwd: './Timber',
      logLevel: 'all',
    }
  )
  .then(res => console.log('Result', res))
  .catch(err => console.error('Error', err));

// Output:
// invalid environment [development]: (invalid theme_id)
// Result undefined

```

### Additional Info

I see there are similar issues (#14 and #19) that were addressed by #23. I am on v1.0.1 but am still seeing problems with error handling.

**Comment by nschomberg** [comment]
Thanks @t-kelly 

Downgrading from `1.0.1` to `1.0.0` seems to fix the issue. My guess is a change in #27 causes errors to be swallowed.

```
const themeKit = require('@shopify/themekit'); // @1.0.0

themeKit
  .command(
    'deploy',
    {
      store: `anything.myshopify.com`,
      password: 'anything',
    },
    {
      cwd: './Timber',
      logLevel: 'all',
    }
  )
  .then(res => console.log('Result', res))
  .catch(err => console.error('Error', err));

// Output:
// Error invalid config invalid environment []: (invalid theme_id,invalid store domain must end in '.myshopify.com')
```

**Comment by t-kelly** [comment]
@harshal317 Could you also tackle this and we'll throw it in the same release as https://github.com/Shopify/node-themekit/pull/35?
