### ISSUE TITLE
Public App Api Key

### ISSUE THREAD

**Issue by pieperz** [Shopify/node-themekit#37]
I am wanting to use node-themekit in a public app to duplicate a theme. 

I have everything working when I use a private app key but when I switch it over to the public app key it does not work and I get the error below. 

`[API] Invalid API key or access token (unrecognized login or wrong password)`

I am able to read and write assets with the normal admin API so I know my app has correct permissions.  

In the [docs](https://shopify.github.io/themekit/#get-api-access), it says to create a private app, but I can't find anywhere stating it will not work with a public app key. 

> To do so, log into the Shopify store, and create a private app. In the Shopify Admin, go to Apps and click on Manage private apps. From there, click Create a new private app, to create your private app.

Are Private App Key's the only way to use theme kit in this way?

**Comment by t-kelly** [comment]
cc @tanema -- I have no idea 😅

**Comment by tanema** [comment]
Honestly, no private apps are not the only way. Private apps work just like public apps but they are just installed right into the shop, however, make sure you are experimenting with the correct key. You cannot just use your API client key, you will have to use the permission access token which is provided to your app after it is installed on the shop. If you are using the correct token and have the appropriate access scopes in place, then I don't see why this wouldn't work however getting it right is a lot more complicated.

**Comment by pieperz** [comment]
Thanks for the info on the private/public that's definitely not documented specifically.

At the moment I just switched this code to use the API instead. 

I do think the keys are the issue I will give it a try if I add this back in.

**Comment by tanema** [comment]
@pieperz Themekit in not necessarily developed to be used with a public app, it was generally thought that if you were a public app that you would consume the theme asset API on your own terms, and I recommend that as well. That way your app is not subject to the changes in themekit.
