### ISSUE TITLE
Unable to retry failed uploads

### ISSUE THREAD

**Issue by nschomberg** [Shopify/node-themekit#39]
### Problem

When an upload error happens, I want to retry uploading that file. Errored filenames get outputted to the terminal, but there is no way to programmatically read those names and handle a retry. 

The only error returned by node-themekit is:

```bash
finished command with errors
```

A list of errored files would be useful for retry handling.

### Replication steps

Run `themeKit.command('deploy', ... );` and cut your internet connection.

### More Information

We experience a lot of upload errors even with a stable internet connection.

**Comment by t-kelly** [comment]
@nschomberg this repo just wraps [Themekit](https://github.com/Shopify/themekit), best to also open an issue there and we can make sure it's supported here once it is added.

**Comment by nschomberg** [comment]
Makes sense, will close this.
