### ISSUE TITLE
Theme 'Watch' Not Returning Errors

### ISSUE THREAD

**Issue by Kehza** [Shopify/node-themekit#40]
If you run the command 'watch' it doesn't return any errors if for example when liquid or JSON is invalid. These do return, if running Theme Kit via command line. 

My Code: 
themeKit.command(
    'watch',
    {
      notify: 'notify.tmp',
    }
  ).catch(err => console.error('Error', err));

Any Ideas? 
Thanks.

**Comment by bdrck** [comment]
Same stuff here. We downgraded to 1.0.1 and added the "verbose: 1" option the the command option. That way we did receive errors. Not sure why this is no longer the case in the new version.

**Comment by Kehza** [comment]
@bdrck Oh? I'll give that a go thanks!

**Comment by ConduciveMammal** [comment]
We're also having this issue, we're currently using v1.1.1 with `verbose: 1`.

Is there a fix likely without having to downgrade?

**Comment by ikolarov** [comment]
It  seems that adding this fixed the issue for me:

https://github.com/ikolarov/node-themekit/commit/096b46d0185512db65d39ecac8e9bfdda210d15a

**Comment by hugoburguete** [comment]
I can't see an issue with @ikolarov 's suggestion. Could we create a PR for it?
