### ISSUE TITLE
Use custom file instead of config.yml?

### ISSUE THREAD

**Issue by YewTreeWeb** [Shopify/node-themekit#42]
Hi, 

Not sure if this is possible but as there is a command to change the working directory for themekit, is there one to use a different file other than config? In my project there are multiple configuration files for example one for Gulp and Webpack so I would like to rename the Shopify config file to either `shopify.config.yml` or `shopify.yml`.

It would be great if I would change this. Thanks for the plugin though and any help would be very appreciated.

Thanks

**Comment by t-kelly** [comment]
I don't think there is an option available. Best open an issue in the main [Themekit](https://github.com/Shopify/themekit) repo as this is just a wrapper.

@tanema, could you please confirm?

**Comment by tanema** [comment]
This already exists. There is a directory option/flag that allows you to specify a path where your theme assets reside.

**Comment by tanema** [comment]
Please see the documentation on the readme for this repo on passing flags to themekit. Then you can find the documentation for themekit flags here: https://shopify.github.io/themekit/configuration/

**Comment by t-kelly** [comment]
@tanema but can you specify the path and name of the config file? My understanding is that Themekit only looks for `config.yml` in the directory specified.

**Comment by tanema** [comment]
Ah sorry I misread this, if you want to use another config file you can use the `--config` flag and give it a path to your config file.

**Comment by t-kelly** [comment]
Thanks Tim! Opened a followup issue https://github.com/Shopify/themekit/issues/646
