### ISSUE TITLE
Command 'Deploy' not returning a 'done' 

### ISSUE THREAD

**Issue by Kehza** [Shopify/node-themekit#57]
When running the command deploy, it doesn't seem to return a 'done' - it just keeps running. Code I am currently using: 

await themeKit.command('deploy', {
    config: params.config_live_yml,
    env: "live",
    verbose: true,
    timeout: "1m",
    files: [
        './layout', 
        './sections', 
        './snippets', 
        './templates/customers', 
        './templates',
        './assets',
        'config/settings_schema.json'
    ]
});

**Comment by andyw8** [comment]
Since we haven't had any further reports of this, I think it may have been due to an intermittent error. Please re-open if you're still having trouble.
