### ISSUE TITLE
Capture output of get --list command

### ISSUE THREAD

**Issue by elkelk** [Shopify/node-themekit#59]
### Problem

I'd love to be able to create a theme and then list the themes and capture the theme id. I'm having issues trying to capture the output of the command either by overwriting `console.log` or capturing STDOUT. Ideally capturing the command response in the library and resolving the promise with the output would allow us to use the response. Any suggestions outside of this?

**Comment by andyw8** [comment]
As this does not appear to be a bug report or specific feature request, I think it would be better suited for the [Partners Community](https://www.shopify.ca/partners/community).

**Comment by elkelk** [comment]
Can we upgrade this to a feature request?
