### ISSUE TITLE
Themekit unable to install

### ISSUE THREAD

**Issue by Noostop** [Shopify/node-themekit#60]
### Problem

User Yarn unable to install.

### Replication steps

Binary is fine
```

> @shopify/themekit@0.6.12 postinstall D:\Desktop\Shopify theme\Noostop\node_modules\@shopify\themekit
> node ./lib/cli.js install
\
```

### More Information

Node version may not be able to download and compile

**Comment by erickzhao** [comment]
Could you provide additional information about your environment?
* `yarn` version
* `node` version
* operating system

**Comment by Noostop** [comment]
> Could you provide additional information about your environment?
> 
> * `yarn`:  v1.22.4
> * `node`:  v12.16.1
> * operating system : windows

**Comment by dan-gamble** [comment]
I think was down to an AWS issue at the time. I remember having this and I ended up doing a `brew install themekit` and you could see it was taking minutes just to get 0.1% of a download. I think it being through NPM was masking this for the node variant

**Comment by andyw8** [comment]
@Noostop I'll close this, bt please let us know if you run into this problem again.
