### ISSUE TITLE
Add support for new --allow-live flag

### ISSUE THREAD

**Issue by andyw8** [Shopify/node-themekit#65]
node-themekit is a wrapper around themekit. Since themekit v1.1.1 there is a new `--allow-flag` (https://github.com/Shopify/themekit/pull/739) which is not yet supported by node-themekit.

`lib/utils.js` would need to updated to allow usage such as:

```javascript
themeKit.command('deploy', {
  allowLive: true
});
```

**Comment by gideonb** [comment]
In the mean time, you can pass in the `'allow-live'` flag as a string:

```js
themekit.command('deploy', {
  'allow-live': true
});
```
_(Thanks to @willbroderick for pointing this out)_

**Comment by md-shuvoislam** [comment]
you just have to add --allow-live at the end of theme watch. So the full command should be

theme watch --allow-live
